spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.177/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  #配置如果返回数据为空将不予显示在对象中
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.31.177
    port: 6379

server:
  context-path: /sell

wechat:
  myAppId: wx24d4b82xxxxxxxxxxx
  myAppSecret: 9345ec385c153f067ed2xxxxxxxxxxx
  myMchId: 1420xxxxxxxxxxx
  myMchKey: 75d0fbdcdxxxxxxxxxxx
  myKeyPath: /var/wechat_cert/h5.p12
  myNotifyUrl: http://xxxxxxxxxxx/sell/pay/notify
  openAppId: wx24d4b824dxxxxxxxxxxx
  openAppSecret: 9345ec385cxxxxxxxxxxx


projectUrl:
  wechatMpAuthorize: http://wx.xxxxxxxxxxx.cn/
  wechatOpenAuthorize: http://wx.xxxxxxxxxxx.cn/
  sell: http://wx.xxxxxxxxxxx.cn/