spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.68/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  #配置如果返回数据为空将不予显示在对象中
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.31.68
    port: 6379

server:
  context-path: /sell

wechat:
  myAppId: wx24d4b824dXXXXXX
  myAppSecret: 9345ec385c153f06XXXXXX
  myMchId: 1420707XXXXXX
  myMchKey: 75d0fbdcd4f1af824eca463XXXXXX
  myKeyPath: /var/wechat_cert/h5.p12
  myNotifyUrl: http://mkmonkey/sell/pay/notify
  openAppId: wx34a6f07e33XXXXXX8
  openAppSecret: 22166d09a6c148e4374bXXXXXX42a9ac81
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEXXXXXX_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://ws.mkmonkey.com
  wechatOpenAuthorize: http://ws.mkmonkey.com
  sell: http://ws.mkmonkey.com